/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import static clases.conexion.getConection;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Crismary
 */
public class apuestaMaxima extends javax.swing.JFrame {
    
    PreparedStatement ps;
   

    /**
     * Creates new form ingresoproductos
     */
    public apuestaMaxima(){ // Constructor
        initComponents();
        mostrardatos(" ");// cuando se inicializa no se le envia ni un parametro para que muestre todos los datos en la tabla
    }
    
    
    ////////////////////////////////////////////////////////////////////////
    
    /////////////////////METODO LIMPIAR CAMPOS/////////////////////////////
    
    ////////////////////////////////////////////////////////////////////////
    
    void limpiarCampos(){
        
//         txtcod.setText(""); //agarramos los daros, lo convertimos en String y lo enviamos al txt correspondiente
         
         txtMonto.setText("");
         txtCod.setText("");
    }
    
    
    
    
   ////////////////////////////////////////////////////////////////////////////
    
   ///////////////////////////Metodo Mostrar todo/////////////////////////////
    
   ////////////////////////////////////////////////////////////////////////////  
    
    void mostrardatos(String valor){  // METODO PARA CREAR LA TABLA
           Connection con = null;
        try {
            
            con = getConection();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("APUESTA MAXIMA");
        tbproductos.setModel(modelo);
        
        String sql = " ";
        if(valor.equals(" ")){ // si el campo valor esta vacio entonces
           
            sql = "SELECT * FROM apuesta_maxima"; // muestra todos los datos
        
        }else{ // si el campo valor no esta vacio entonces
            
            sql = "SELECT * FROM apuesta_maxima WHERE monto_maximo='"+valor+"'"; // selecciona el que tenga el codigo iguan al campo valor
            
        }
   // String codigo = "0001";
        
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);  //Almacena los datos de la consulta que vamos a realizar
        String [] datos = new String [2]; //Variable donde se guardan los datos que nos traemos de la tabla 
    while(rs.next()){                   //Mostramos los datos
        
          datos[0] = rs.getString(1); // Lo que esta en rs, lo guardo en la posicion 0 del arreglo dato
          datos[1] = rs.getString(2);
          
          modelo.addRow(datos); // Capturamos la fila con la informacion 
    }
    
        tbproductos.setModel(modelo); // Mostramos los datos en la tabla 
            
        } catch (Exception e) {
          }
    
       
  }
    
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MenuEmergenteModificar = new javax.swing.JMenuItem();
        MenuEmergenteEliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        btngrabar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproductos = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnMostrarTodosLosDatos = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        MenuEmergenteModificar.setText("Modificar");
        MenuEmergenteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmergenteModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MenuEmergenteModificar);

        MenuEmergenteEliminar.setText("Eliminar");
        MenuEmergenteEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmergenteEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MenuEmergenteEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apuesta maxima");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        jLabel1.setText("Codigo :");

        jLabel3.setText("Monto :");

        txtCod.setEditable(false);

        btngrabar.setText("Grabar");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btngrabar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCod, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addGap(162, 162, 162))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addComponent(btngrabar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbproductos.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tbproductos);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnMostrarTodosLosDatos.setText("Mostrar todos los datos");
        btnMostrarTodosLosDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosLosDatosActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnBuscar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnActualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMostrarTodosLosDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnMostrarTodosLosDatos)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        
        Connection con = null;
        
        try{
            
            con = getConection();
            ps = con.prepareStatement("INSERT INTO apuesta_maxima(monto_maximo )VALUE (?)");
            //ps.setString(1, txtcod.getText());
            
            ps.setString(1, txtMonto.getText());
            
            
            int res = ps.executeUpdate();
           
            mostrardatos(" "); // metodo para que cuando grabe, se muestren todos los datos de la tabla
            
            if(res > 0){
                
                JOptionPane.showMessageDialog(null, "Monto registrado");
             
            }else {
                
                JOptionPane.showMessageDialog(null, "Error al guardar");
              
            }
            
            con.close();
        }
        catch(Exception e){
            
            System.out.println("");
            JOptionPane.showMessageDialog(null, "Ya existe un producto con ese codigo");
            
            
        }
        
        limpiarCampos();
        
        
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
        mostrardatos(txtbuscar.getText()); // le pasa como parametro lo que tiene el txtbuscar
        txtbuscar.setText("");
                
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostrarTodosLosDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosLosDatosActionPerformed
         mostrardatos(" "); // muestra todos los datos en la tabla
    }//GEN-LAST:event_btnMostrarTodosLosDatosActionPerformed

    ////////////////////////////////////////////////////////////////////////
    /////////////////esto es la accion del popumenu menu emergente(modificar)
    /////////////////////////////////////////////////////////////////////////
    
    
    private void MenuEmergenteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmergenteModificarActionPerformed
       
       int fila = tbproductos.getSelectedRow(); //con esto guardo en la variable  fila el numero de la fila seleccionada
       if (fila >= 0){ // si la fila es mayor a cero, enviamos los datos que esta en esa fila, hacia los textbox
       
           //txtcod.setText(tbproductos.getValueAt(fila, 0).toString()); //agarramos los daros, lo convertimos en String y lo enviamos al txt correspondiente
           
           txtCod.setText(tbproductos.getValueAt(fila, 0).toString());
           txtMonto.setText(tbproductos.getValueAt(fila, 1).toString());
       
       }
       else{
       
             JOptionPane.showMessageDialog(null, "No selecciono fila");
       
       }
          
    }//GEN-LAST:event_MenuEmergenteModificarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        Connection con = null;
        
        try{
            
            con = getConection();
            ps = con.prepareStatement("UPDATE apuesta_maxima SET  monto_maximo = '"+txtMonto.getText()+"' WHERE idmonto_maximo = '"+txtCod.getText()+"'");
           
            
            
            int res = ps.executeUpdate();
           
            mostrardatos(" "); // metodo para que cuando grabe, se muestren todos los datos de la tabla
            
            if(res > 0){
                
                JOptionPane.showMessageDialog(null, "Monto modificado");
             
            }else {
                
                JOptionPane.showMessageDialog(null, "Error al modificar");
              
            }
            
            con.close();
        }
        catch(Exception e){
            
            System.out.println("");
            JOptionPane.showMessageDialog(null, "Ya existe un producto con ese codigo");
            
            
        }
            limpiarCampos();     
         
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void MenuEmergenteEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmergenteEliminarActionPerformed
        
        int fila = tbproductos.getSelectedRow(); //con esto guardo en la variable  fila el numero de la fila seleccionada
        String cod ="";
        cod = tbproductos.getValueAt(fila, 0).toString(); //Hay que convertirlo en un String
        
        
        Connection con = null;
        
        try{
            
            con = getConection();
            ps = con.prepareStatement("DELETE FROM apuesta_maxima WHERE  idmonto_maximo= '"+cod+"'");
           
            
            
            int res = ps.executeUpdate();
           
            mostrardatos(" "); // metodo para que cuando grabe, se muestren todos los datos de la tabla
            
            if(res > 0){
                
                JOptionPane.showMessageDialog(null, "Monto eliminado");
             
            }else {
                
                JOptionPane.showMessageDialog(null, "Error al eliminar");
              
            }
            
            con.close();
        }
        catch(Exception e){
            
            System.out.println("");
            JOptionPane.showMessageDialog(null, "Ya existe un producto con ese codigo");
            
            
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_MenuEmergenteEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apuestaMaxima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apuestaMaxima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apuestaMaxima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apuestaMaxima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                new apuestaMaxima().setVisible(true);
               // new apuestaMaxima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuEmergenteEliminar;
    private javax.swing.JMenuItem MenuEmergenteModificar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrarTodosLosDatos;
    private javax.swing.JButton btngrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbproductos;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables

   
//con = getConection();

}
